Доработана информация по техническому заданию спринта
Ne0niy/java-kanban pull request #2
Opened 2024-07-01 18:31 UTC by Ne0niy

2024-07-01 20:53 UTC, Yang-Pi requested changes

2024-07-01 20:53 UTC, Yang-Pi commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +    private int size;
Размер уже не нужен по ТЗ, для его определения можно уровне historyTaskMap вызвать метод size()

2024-07-01 20:53 UTC, Yang-Pi commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +        history.removeNode(historyTaskMap.get(id));
Также нужно удалить и элемент из мапы

2024-07-01 20:53 UTC, Yang-Pi commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +            head = null;
Они уже null, судя по условию, поэтому можно просто ничего не делать

2024-07-05 20:17 UTC, Ne0niy commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +    private int size;
Удалил переменную size, взамен добавил метод size

2024-07-05 20:19 UTC, Ne0niy commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +        history.removeNode(historyTaskMap.get(id));
Дополнил метод remove, также обновил тест remove

2024-07-05 20:33 UTC, Ne0niy commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +            head = null;
Без этого условия, в тестах проявляется NullPointerException

2024-07-05 21:16 UTC, Yang-Pi commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +            head = null;
Дело не в условии, а в том, что не нужно занулять переменные, просто выйти из метода

2024-07-05 21:18 UTC, Yang-Pi requested changes

2024-07-05 21:18 UTC, Yang-Pi commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Не увидел использование этого метода в рамках менеджера задач - нужно добавить

2024-07-06 17:09 UTC, Ne0niy commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +    public void remove(int id) {
Добавил новые и дополнил старые

2024-07-06 17:27 UTC, Ne0niy commented on src/main/java/ru/practicum/service/InMemoryHistoryManager.java
> +            head = null;
Я понимаю, тоже так думал, но если их не привести к null, то в тестах происходит исключение

2024-07-13 17:27 UTC, merged